import type { Workout } from './types';

export const defaultWorkouts: Workout[] = [
  {
    id: 'default-morning',
    title: 'Утренняя зарядка',
    exercises: [
      {
        title: 'Наклоны головы',
        description: 'Плавные наклоны головы вперёд, назад, влево, вправо',
        repeatCount: 8,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 2, hold: 1, from: 2 },
      },
      {
        title: 'Вращения плечами',
        description: 'Круговые движения плечами вперёд и назад',
        repeatCount: 10,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 1, hold: 0, from: 1 },
      },
      {
        title: 'Наклоны туловища в стороны',
        description: 'Наклоны влево и вправо с рукой над головой',
        repeatCount: 10,
        setCount: 2,
        restSeconds: 20,
        tempo: { to: 1, hold: 1, from: 1 },
      },
      {
        title: 'Приседания',
        description: 'Классические приседания, спина прямая, колени не выходят за носки',
        repeatCount: 12,
        setCount: 3,
        restSeconds: 30,
        tempo: { to: 2, hold: 0, from: 2 },
      },
      {
        title: 'Махи ногами',
        description: 'Махи прямой ногой вперёд, чередуя ноги',
        repeatCount: 10,
        setCount: 2,
        restSeconds: 20,
        tempo: { to: 1, hold: 0, from: 1 },
      },
      {
        title: 'Прыжки на месте',
        description: 'Лёгкие прыжки с разведением рук и ног (jumping jacks)',
        repeatCount: 20,
        setCount: 2,
        restSeconds: 30,
        tempo: { to: 1, hold: 0, from: 1 },
      },
    ],
  },
  {
    id: 'default-work-break',
    title: 'Разминка на работе',
    exercises: [
      {
        title: 'Вращения головой',
        description: 'Медленные полукруговые вращения головой',
        repeatCount: 8,
        setCount: 1,
        restSeconds: 10,
        tempo: { to: 2, hold: 0, from: 2 },
      },
      {
        title: 'Разведение рук в стороны',
        description: 'Поднимите руки в стороны и сведите лопатки',
        repeatCount: 10,
        setCount: 2,
        restSeconds: 10,
        tempo: { to: 1, hold: 1, from: 1 },
      },
      {
        title: 'Повороты туловища',
        description: 'Повороты корпуса влево и вправо, таз неподвижен',
        repeatCount: 10,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 1, hold: 1, from: 1 },
      },
      {
        title: 'Наклоны к ногам стоя',
        description: 'Наклон вперёд, тянитесь руками к полу, ноги прямые',
        repeatCount: 8,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 2, hold: 2, from: 2 },
      },
      {
        title: 'Подъёмы на носки',
        description: 'Поднимитесь на носки и медленно опуститесь',
        repeatCount: 15,
        setCount: 2,
        restSeconds: 10,
        tempo: { to: 1, hold: 1, from: 1 },
      },
    ],
  },
  {
    id: 'default-evening-stretch',
    title: 'Вечерняя растяжка',
    exercises: [
      {
        title: 'Наклон к ногам сидя',
        description: 'Сядьте на пол, ноги прямые, тянитесь руками к стопам',
        repeatCount: 6,
        setCount: 2,
        restSeconds: 20,
        tempo: { to: 2, hold: 3, from: 2 },
      },
      {
        title: 'Растяжка квадрицепса',
        description: 'Стоя, согните ногу и притяните пятку к ягодице, чередуя ноги',
        repeatCount: 6,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 2, hold: 3, from: 2 },
      },
      {
        title: 'Поза кошки-коровы',
        description: 'На четвереньках: прогните спину вниз (корова), затем округлите вверх (кошка)',
        repeatCount: 10,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 2, hold: 1, from: 2 },
      },
      {
        title: 'Скручивания лёжа',
        description: 'Лёжа на спине, колени согнуты, опускайте их влево и вправо',
        repeatCount: 8,
        setCount: 2,
        restSeconds: 20,
        tempo: { to: 2, hold: 2, from: 2 },
      },
      {
        title: 'Поза ребёнка',
        description: 'Сядьте на пятки, наклонитесь вперёд, руки вытянуты, расслабьтесь',
        repeatCount: 4,
        setCount: 2,
        restSeconds: 15,
        tempo: { to: 2, hold: 5, from: 2 },
      },
    ],
  },
];
